apiVersion: v1
kind: Service
metadata:
  name: package-audit
  namespace: audit-system
spec:
  type: NodePort
  selector:
    app: package-audit
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30081
