apiVersion: v1
kind: PersistentVolume
metadata:
  name: package-audit-packages-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.0.2.164
    path: /export/packages
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: package-audit-packages-pvc
  namespace: audit-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
